meta_product_name: "TakeOff"
meta_title: "TakeOff - Group Holidays, made Simple"
meta_description: "TakeOff is a WebApp that helps you organize your group holidays via an invitation system, a setup by topic on which you can vote for your favorite suggestion and a feature to share expenses with your friends."
meta_image: "favicon.ico"